version: '2'
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 33060:33060
      - 3306:3306
    environment:
      - MYSQL_DATABASE=training
      - MYSQL_ROOT_PASSWORD=training
